language: node_js
node_js:
    - '0.12'
    - '0.11'
    - '0.10'
script:
  npm run lint && npm run coverage

after_script:
  - "[ -d ./coverage ] && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"